//autogenerated by msp430-gen.py
#ifndef _PINS_H
#define _PINS_H

#define CLOCK_PINS        (BIT2|BIT5|BIT4)
#define CLOCK_DIR         P1DIR
#define CLOCK_SEL0        P1SEL0
#define CLOCK_SEL1        P1SEL1

#define UART_TX_PIN       BIT3
#define UART_RX_PIN       BIT4
#define UART_TX_PIN_NUM   3
#define UART_RX_PIN_NUM   4
#define UART_PINS         (UART_RX_PIN|UART_TX_PIN)
#define UART_PORT         4

//define serial pins
#define BUS_PIN_SDA       BIT1
#define BUS_PIN_SCL       BIT0

#define BUS_PINS_I2C      (BUS_PIN_SDA|BUS_PIN_SCL)

#define BUS_PIN_SCK       BIT2
#define BUS_PIN_SOMI      BIT3
#define BUS_PIN_SIMO      BIT4
  
#define BUS_PINS_SPI      (BUS_PIN_SOMI|BUS_PIN_SIMO|BUS_PIN_SCK)  

#define BUS_PINS_SER      (BUS_PINS_SPI|BUS_PINS_I2C)
#define ON  1 
#define OFF 2

//define LED Control Pins 
#define LED0    BIT3
#define LED1    BIT4
#define LED2    BIT5
#define LED3    BIT6
#define LED4    BIT7
#define LED_PORT_DIR P7DIR
#define LED_PORT_OUT P7OUT
#define LED_PORT_DS P7DS

#define LED_CONTROL_X         BIT0
#define LED_CONTROL_X_DIR     P7DIR
#define LED_CONTROL_X_OUT     P7OUT
#define LED_CONTROL_X_DS      P7DS
#define LED_CONTROL_Y         BIT2
#define LED_CONTROL_Y_DIR     P4DIR
#define LED_CONTROL_Y_OUT     P4OUT
#define LED_CONTROL_Y_DS      P4DS


//define voltage control pins 
#define CLYDE_TEMP_VCC_PIN         BIT4
#define CLYDE_SDCARD_VCC_PIN       BIT0
#define CLYDE_ACC_VCC_PIN          BIT2
#define CLYDE_BACK_PLANCE_VCC_PIN  BIT6

#define LEDL_TEMP_VCC_PIN          BIT5
#define LEDL_SDCARD_VCC_PIN        BIT1
#define LEDL_ACC_VCC_PIN           BIT3
#define LEDL_BACK_PLANCE_VCC_PIN   BIT7

#define SENSOR_POWER_RAIL_PORT     6

#define SENSORS_DIR   P6DIR
#define SENSORS_OUT   P6OUT
#define SENSORS_DS    P6DS


//define LEDL Regulator power pins 
#define LEDL_BLOW_FUSE              BIT5
#define LEDL_REGULATOR_ON_OFF       BIT6
#define LEDL_REGULATOR_DIR          P3DIR
#define LEDL_REGULATOR_OUT          P3OUT
#define LEDL_REGULATOR_DS           P3DS
 
//define LEDL INTERRUPTS 
#define GYRO_INTERRUPT                BIT3
#define ACCEL_INTERRUPT1              BIT4
#define ACCEL_INTERRUPT2              BIT5
#define LOG_DATA_EXTERNAL_SWITCH      BIT6
#define LAUNCH_DETECTED               BIT7
#define INTERRUPT_DIR                 P1DIR
#define INTERRUPT_OUT                 P1OUT
#define INTERRUPT_ENABLE              P1EN


//define LEDL Control Pins
#define LUX5_VCC_CONT8                BIT1
#define LUX4_VCC_CONT7                BIT7                
#define LUX3_VCC_CONT6                BIT0
#define LUX2_VCC_CONT5                BIT7
#define LUX1_VCC_CONT4                BIT6
#define GYRO_SA0_CONT3                BIT5
#define GYRO_DATA_READY_INT_2_CONT2   BIT4
#define GYRO_CS_CONT1                 BIT3

#define LUX14_DIR   P5OUT
#define LUX_2_DIR   P3OUT
#define LUX35_DIR   P8OUT

#define LUX14_OUT   P5OUT
#define LUX_2_OUT   P3OUT
#define LUX35_OUT   P8OUT

#define LUX14_DS    P5DS
#define LUX_2_DS    P3DS
#define LUX35_DS    P8DS



#endif
